project:
  type: website
  output-dir: docs

website:
  title: "Simulation Tutorial Blog"
  description: "A simple walkthrough of simulation in the context of statistical analysis"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "About Me"
        href: about.md
      - text: "Projects"
        menu:
          - text: "All Projects"
            href: projects/index.md
          - text: "---"
          - text: "Exploratory Data Analysis"
            href: projects/eda.qmd
          - text: "Data Acquisition"
            href: projects/data-acquisition.qmd
          - text: "Final Project"
            href: projects/final-project.qmd
    right:
      - icon: github
        href: https://github.com/your-username
      - icon: linkedin
        href: https://linkedin.com/in/your-profile


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
